apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bookissuerequests.testing.fabric8.io
spec:
  group: testing.fabric8.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                to:
                  type: string
                name:
                  type: string
            status:
              type: object
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: bookissuerequests
    singular: bookissuerequest
    kind: BookIssueRequest
    shortNames:
      - bir
