apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: librarybookoperator
    namespace: default
roleRef:
  kind: Role
  name: library-reader-writer
  apiGroup: rbac.authorization.k8s.io
