apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.testing.fabric8.io
spec:
  group: testing.fabric8.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                isbn:
                  type: string
            status:
              type: object
              properties:
                issued:
                  type: boolean
                issuedto:
                  type: string      
      subresources:
        status: {}  
  scope: Namespaced
  names:
    plural: books
    singular: book
    kind: Book
    shortNames:
    - book
